/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.opencv.core.Core;

public class App {

    public static void main(String[] args) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);

        if (args.length < 1) {
            System.out.println("Uso: java Main <v|r> ...");
            return;
        }

        char modo = args[0].charAt(0);

        try {
            if (modo == 'v' || modo == 'V') {
                Video.main(args);
            } else if (modo == 'r' || modo == 'R') {
                Rotaciona.main(args);
            } else {
                System.out.println("Primeiro parâmetro deve ser 'v' ou 'r'.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
