/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.opencv.core.*;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.Imgproc;


public class Rotaciona{

	public static void main(String[] args) throws Exception {
        // Uso: r <imagemEntrada> <imagemSaida> <angulo>
        if (args.length < 3) {
            System.out.println("Uso: java Main r <imagemEntrada> <imagemSaida> <angulo>");
            return;
        }

        String path = args[1];
        double angulo = Double.parseDouble(args[3]);
        String imagemSaida = args[2];

        Mat img = Imgcodecs.imread(path);
        if (img.empty()) {
            System.out.println("Erro ao carregar imagem: " + path);
            return;
        }

        int w = img.cols();
        int h = img.rows();

        Point centro = new Point(w / 2.0, h / 2.0);

        Mat m = Imgproc.getRotationMatrix2D(centro, angulo, 1.0);

        Mat rot = new Mat();
        Imgproc.warpAffine(img, rot, m, new Size(w, h));

        Imgcodecs.imwrite(imagemSaida, rot);
        System.out.println("Imagem salva: " + imagemSaida);
    }
}
