/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.opencv.core.*;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.Imgproc;
import org.opencv.videoio.VideoWriter;

public class Video {

    public static void main(String[] args) {

        // Uso: v <imagem> <saida.mp4> <duracao>
        if (args.length < 4) {
            System.out.println("Uso: java Main v <imagem> <saida> <duracao_seg>");
            return;
        }

        String pathImg = args[1];
        String pathVideo = args[2];
        double duracao = Double.parseDouble(args[3]);

        double fps = 30.0;
        int totalFrames = (int) (duracao * fps);

        Mat img = Imgcodecs.imread(pathImg);
        if (img.empty()) {
            System.out.println("Erro ao carregar imagem: " + pathImg);
            return;
        }

        int w = img.cols();
        int h = img.rows();

        // MJPEG — sempre funciona
        int fourcc = VideoWriter.fourcc('M', 'J', 'P', 'G');

        VideoWriter writer = new VideoWriter(
                pathVideo,
                fourcc,
                fps,
                new Size(w, h)
        );

        if (!writer.isOpened()) {
            System.out.println("Erro ao abrir video: " + pathVideo);
            return;
        }

        for (int i = 0; i < totalFrames; i++) {
            double ang = 360.0 * i / totalFrames;

            Point centro = new Point(w / 2.0, h / 2.0);
            Mat matriz = Imgproc.getRotationMatrix2D(centro, ang, 1.0);

            Mat frame = new Mat();
            Imgproc.warpAffine(img, frame, matriz, new Size(w, h));

            writer.write(frame);

            System.out.printf("\rFrame %d/%d  Angulo %.2f", i+1, totalFrames, ang);
        }

        System.out.println("\nVídeo gerado: " + pathVideo);
        writer.release();
    }
}
